services:
  soccer.font-end:
    image: ${DOCKER_REGISTRY-}soccerfrontend
    build:
      context: .
      dockerfile: Soccer.Font-end/Dockerfile
    ports:
      - "7170:7170"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      # Nếu muốn chạy HTTPS cho front-end, giữ nguyên 2 biến dưới đây
      ASPNETCORE_Kestrel__Certificates__Default__Password: "Duong@123"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/aspnetapp.pfx"
    volumes:
      - ${USERPROFILE}/.aspnet/https:/https:ro
    networks:
      - demo

networks:
  demo:
    driver: bridge
