
services:
  soccer.business-logic:
    image: ${DOCKER_REGISTRY-}soccerbusinesslogic
    build:
      context: .
      dockerfile: Soccer.Business-Logic/Dockerfile
    ports:
      - "8085:80"   # HTTP
      - "8444:443"  # HTTPS
    environment:
      ASPNETCORE_URLS: "https://+:443;http://+:80"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "Duong@123"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/aspnetapp.pfx"
      TZ: "Asia/Ho_Chi_Minh"
    volumes:
      - ${USERPROFILE}/.aspnet/https:/https:ro

    networks:
      - demo

  # ==========================
  # Service Front-end: soccer.font-end
  # ==========================
  soccer.font-end:
    image: ${DOCKER_REGISTRY-}soccerfrontend
    build:
      context: .
      dockerfile: Soccer.Font-end/Dockerfile
    ports:
      - "5000:8080"   # ánh xạ host:5000 → container:8080 (Front-end HTTP)
      - "5001:8081"   # ánh xạ host:5001 → container:8081 (Front-end HTTPS)
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      # Nếu muốn chạy HTTPS cho front-end, giữ nguyên 2 biến dưới đây
      ASPNETCORE_Kestrel__Certificates__Default__Password: "Duong@123"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/aspnetapp.pfx"
    volumes:
      - ${USERPROFILE}/.aspnet/https:/https:ro
    networks:
      - demo

networks:
  demo:
    driver: bridge

