services:
  soccer.font-end:
    container_name: soccer-font-end
    build:
      context: .
      dockerfile: Soccer.Font-end/Dockerfile
    ports:
      - "7170:8080"  # HTTP API
    environment:
      - ASPNETCORE_URLS=http://+:8080/
    networks:
      - demo
  soccer.business-logic:
    image: ${DOCKER_REGISTRY-}soccerbusinesslogic
    ports:
      - "7237:8080"
    build:
      context: .
      dockerfile: Soccer.Business-Logic/Dockerfile

networks:
  demo:
    driver: bridge
